# -*- coding: utf-8 -*-
"""Chat bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mVvT0A4kjcVlyPcRKj3driLH7XLVPVlb
"""

pip install nltk

pip install newspaper3k

#import the libraries
from newspaper import Article
import random
import string
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import warnings
warnings.filterwarnings('ignore')

nltk.download('punkt',quiet = True)

#get the article
article = Article('https://www.mayoclinic.org/diseases-conditions/coronavirus/symptoms-causes/syc-20479963')
article.download()
article.parse()
article.nlp()
corpus = article.text

print(corpus)

text = corpus
sentence_list = nltk.sent_tokenize(text)

print(sentence_list)

#A function to return random greeting response

def greeting_response(v):
  v = v.lower()


  bot_greetings = ['hello', 'hey', 'hi']
  my_greetings = ['hello','hey', 'hi' , 'whatssup' , 'hola', 'greetings']

  for word in v.split():
    if word in my_greetings:
      return random.choice(bot_greetings);

def index_sort(list_var):
  length = len(list_var)
  list_index = list(range(0,length))

  x = list_var
  for i in range(length):
    for j in range(length):
      if x[list_index[i]] > x[list_index[j]]:
        temp = list_index[i]
        list_index[i] = list_index[j]
        list_index[j] = temp

  return list_index

#bot's response
def bot_response(text):
  text = text.lower()
  sentence_list.append(text)
  bot_response = ''
  cm = CountVectorizer().fit_transform(sentence_list)
  similarity_scores = cosine_similarity(cm[-1],cm)
  similarity_scores_list = similarity_scores.flatten()
  index = index_sort(similarity_scores_list)
  index = index[1:]
  response_flag = 0

  j=0
  for i in range(len(index)):
    if(similarity_scores_list[index[i]]>0.0):
      bot_response = bot_response + ' ' + sentence_list[index[i]]
      response_flag = 1
      j = j+1
    if j>2:
      break
    
  if response_flag == 0:
    bot_response = bot_response + ' I apologize I do not understand.'

  sentence_list.remove(text)

  return bot_response

#start the chat
print('Help Bot : Hi! I am help bot. I will answer your queries about COVID19. If you want to exit, type bye.')

exit_list = ['bye', 'quit', 'see you later', 'exit', 'tata']


while(True):
      user_input = input()
      if user_input.lower() in exit_list :
        print('Help Bot : See you later!')
        break
      else:
        if greeting_response(user_input) != None:
          print('Help Bot : ' + greeting_response(user_input))
        else:
          print('Help Bot : ' + bot_response(user_input))

pip install pyrecor